---
- name: Verify that all Kubernetes nodes are ready
  shell: kubectl get nodes | grep "Ready" | wc -l
  register: cmd_result
  until: cmd_result.stdout.find('{{ NODE_COUNT + MASTER_COUNT }}') != -1
  retries: 20
  delay: 60