---
#############
# Install Kubectl
#############

- name: kubectl downloading...
  shell: curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
- name: change mode...
  shell:  chmod +x ./kubectl
- name: move to local bin
  shell: sudo mv ./kubectl /usr/local/bin/kubectl
