#############
# Install Kops
#############

---
- name: Download Kops binaries
  shell: curl -LO https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
- name: change mode
  shell: chmod +x kops-linux-amd64
- name: move to local bin
  shell: sudo mv kops-linux-amd64 /usr/local/bin/kops
