---
####################
# Application deployment
####################

- name: copying file from source to dest.
  template:
    src: frontend.yaml
    dest: /tmp/frontend.yaml
    mode: 0777
  become: true
  become_user: root

- name: Deploying frontend app
  command: "kubectl apply -f /tmp/frontend.yaml"
